### ISSUE TITLE
Document minimal version of composer required for vendor-expose in 4.1

### ISSUE THREAD

**Issue by stojg** [silverstripe/vendor-plugin#23]
## Affected Version

```
phpunit/phpunit            5.7.27 The PHP Unit Testing framework.
silverstripe-themes/simple 3.2.0  The SilverStripe simple theme (default SilverStripe 3 theme)
silverstripe/recipe-cms    4.1.2  SilverStripe recipe for fully featured page and asset content editing
silverstripe/recipe-plugin 1.3.0  Helper plugin to install SilverStripe recipes
silverstripe/vendor-plugin 1.3.3  Allows vendor modules to expose directories to the webroot
```

## Description
Following the guides at https://docs.silverstripe.org/en/4/upgrading/ and using the latest silverstripe-installer project they did not tell me or warn me about the version of composer required to run vendor-expose locally.

```
$ composer --version
Composer 1.5.2 2017-09-11 16:59:25

$ composer vendor-expose                                                               
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "vendor-expose" is not defined. 

$ silverstripe/vendor-plugin         1.3.3   Allows vendor modules to expose directories to the webroot
```

As it turned out, I needed to upgrade composer 
```
$ composer --version
Composer version 1.6.5 2018-05-04 11:44:59
```

And then `composer vendor-expose` works like a charm

# Related Pull Request
* [x] https://github.com/silverstripe/silverstripe-framework/pull/8296

**Comment by maxime-rainville** [comment]
I'm not sure there's a way to explicitly say in the vendor-plugin's composer file that you need to use a specific version of composer. Since the vendor-plugin will never be reach if you use an old version of composer, we can't show a warning either.

I guess we could add some silly command to `pre-install-cmd` i nthe installer's composer file that tries check which version of composer you are using, but that sounds hackish.

The best thing we can do is mention it in the doc.

**Comment by stojg** [comment]
Any documentation in the main upgrade/install guides would be a start

**Comment by stojg** [comment]
weird. maybe that was the case in my scenario. feel free to close if you feel this is not worth investigating further.

**Comment by maxime-rainville** [comment]
I've tested with composer 1.1 and it worked for me. It probably wouldn't hurt to have a few lines in the upgrade guide about it to cover our basis.

**Comment by maxime-rainville** [comment]
I've updated the upgrade guide to explicitly state that you need to use composer 1.1 or greater.

As mentioned, there's not really an elegant way of notifying developers if they are using an outdated version of composer. Composer 1.1 has been out for over 2 years now, so that should hopefully not affect many people.
